[package]
name = "moyu_reader"
version = "0.1.0"
authors = ["Your Name <you@example.com>"]
edition = "2021"

[dependencies]
tauri = { version = "2.9.1" }

[build-dependencies]
tauri-build = { version = "2.5.1" }

[features]
default = ["custom-protocol"]
custom-protocol = []
